name: Build and Deploy Site

on:
  push:
    branches:
      - master  # Triggers the workflow on changes to the master branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Specifies the runner environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Build site
      run: python make_site.py

    - name: List output directory contents
      run: ls -la output

    - name: Copy CNAME to output directory
      run: cp CNAME.txt output/CNAME  # Adjust the source file name if necessary

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
        force_orphan: true  # Consider setting this to false if you want to retain commit history
