name: Build and Deploy Site

on:
  push:
    branches:
      - master  # Trigger the workflow on changes to the master branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Specifies the runner environment

    steps:
    - uses: actions/checkout@v2  # Checks out your repository under $GITHUB_WORKSPACE

    - name: Set up Python
      uses: actions/setup-python@v2  # Sets up Python
      with:
        python-version: '3.x'  # Specify the Python version

    - name: Install dependencies
      run: pip install -r requirements.txt  # Install dependencies

    - name: Build site
      run: python make-site.py  # Run your build command

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3  # Deploys to the gh-pages branch
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
        publish_dir: ./output  # Directory to publish
